"""empty message

Revision ID: 609ebedf37c2
Revises: e438bccc9589
Create Date: 2023-12-26 15:56:31.013310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "609ebedf37c2"
down_revision = "e438bccc9589"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("image", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("0"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("name", name=op.f("uq_categories_name")),
    )
    op.create_table(
        "restaurants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("image", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=False),
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("duration", sa.String(length=256), nullable=False),
        sa.Column("location", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_restaurants")),
        sa.UniqueConstraint("name", name=op.f("uq_restaurants_name")),
    )
    op.create_table(
        "rates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("restaurant_id", sa.Integer(), nullable=False),
        sa.Column("rate", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurants.id"],
            name=op.f("fk_rates_restaurant_id_restaurants"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_rates_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rates")),
        sa.UniqueConstraint("uuid", name=op.f("uq_rates_uuid")),
    )
    op.create_table(
        "restaurant_categories",
        sa.Column("restaurant_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_restaurant_categories_category_id_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurants.id"],
            name=op.f("fk_restaurant_categories_restaurant_id_restaurants"),
        ),
        sa.PrimaryKeyConstraint(
            "restaurant_id", "category_id", name=op.f("pk_restaurant_categories")
        ),
    )
    op.create_table(
        "restaurant_rates",
        sa.Column("restaurant_id", sa.Integer(), nullable=False),
        sa.Column("rate_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rate_id"], ["rates.id"], name=op.f("fk_restaurant_rates_rate_id_rates")
        ),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurants.id"],
            name=op.f("fk_restaurant_rates_restaurant_id_restaurants"),
        ),
        sa.PrimaryKeyConstraint(
            "restaurant_id", "rate_id", name=op.f("pk_restaurant_rates")
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("restaurant_rates")
    op.drop_table("restaurant_categories")
    op.drop_table("rates")
    op.drop_table("restaurants")
    op.drop_table("categories")
    # ### end Alembic commands ###
