"""food

Revision ID: c81af9fb365a
Revises: 124d856dfbb1
Create Date: 2024-01-11 16:55:04.851177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c81af9fb365a'
down_revision = '124d856dfbb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('img', sa.String(length=255), nullable=False),
    sa.Column('info', sa.Text(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_foods_restaurant_id_restaurants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_foods')),
    sa.UniqueConstraint('uuid', name=op.f('uq_foods_uuid'))
    )
    op.create_table('food_tags',
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_food_tags_category_id_categories')),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], name=op.f('fk_food_tags_food_id_foods')),
    sa.PrimaryKeyConstraint('food_id', 'category_id', name=op.f('pk_food_tags'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_tags')
    op.drop_table('foods')
    # ### end Alembic commands ###
